// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxMWj9p44fmSbTCdhcpKqx5hzU5JrqI80',
    appId: '1:107430154148:web:a2d0b9761cdc2f9bdafb31',
    messagingSenderId: '107430154148',
    projectId: 'datingapp-5bc87',
    authDomain: 'datingapp-5bc87.firebaseapp.com',
    storageBucket: 'datingapp-5bc87.appspot.com',
    measurementId: 'G-KG78RDJNDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdbVW5M_3uifk8pH7yaYyRYCvSVzytKbU',
    appId: '1:107430154148:android:230c236dcc1e7e43dafb31',
    messagingSenderId: '107430154148',
    projectId: 'datingapp-5bc87',
    storageBucket: 'datingapp-5bc87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw5Di_0Vong77A6jiuE8zwS1pWZCAfTEY',
    appId: '1:107430154148:ios:a6685a98f26b6715dafb31',
    messagingSenderId: '107430154148',
    projectId: 'datingapp-5bc87',
    storageBucket: 'datingapp-5bc87.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw5Di_0Vong77A6jiuE8zwS1pWZCAfTEY',
    appId: '1:107430154148:ios:a6685a98f26b6715dafb31',
    messagingSenderId: '107430154148',
    projectId: 'datingapp-5bc87',
    storageBucket: 'datingapp-5bc87.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxMWj9p44fmSbTCdhcpKqx5hzU5JrqI80',
    appId: '1:107430154148:web:5c9035b483916f49dafb31',
    messagingSenderId: '107430154148',
    projectId: 'datingapp-5bc87',
    authDomain: 'datingapp-5bc87.firebaseapp.com',
    storageBucket: 'datingapp-5bc87.appspot.com',
    measurementId: 'G-N3N71W0BN1',
  );
}
